spring.application.name=Bookhub
server.servlet.context-path=/bookhub-club/api

spring.datasource.url=jdbc:postgresql://localhost:5432/bookhub
spring.datasource.username=postgres
spring.datasource.password=super

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

jwt.secret=cdf40099c4da4451480d4281c8d69f0fee873371882918272a83cba27ecce7af584b505d419c6f2a50aa38111143c9331cb9c99605f79701b72f41de838e8fb0

app.reservation.expiration.cron=0 0 6 * * *