-- INSERT INTO etats (libelle) VALUES ('Disponible');
-- INSERT INTO etats (libelle) VALUES ('Réservé');
-- INSERT INTO etats (libelle) VALUES ('Emprunté');
-- INSERT INTO etats (libelle) VALUES ('Inutilisable');
--
-- INSERT INTO statuts (libelle) VALUES ('Sur liste d''attente');
-- INSERT INTO statuts (libelle) VALUES ('En attente de retrait');
-- INSERT INTO statuts (libelle) VALUES ('Cloturée');
-- INSERT INTO statuts (libelle) VALUES ('Annulée');
--
-- INSERT INTO genres (libelle) VALUES ('Art poétique');
-- INSERT INTO genres (libelle) VALUES ('Roman policier');
-- INSERT INTO genres (libelle) VALUES ('Fantaisie');
-- INSERT INTO genres (libelle) VALUES ('Théâtre');
-- INSERT INTO genres (libelle) VALUES ('Argumentatif');
-- INSERT INTO genres (libelle) VALUES ('Graphique');
-- INSERT INTO genres (libelle) VALUES ('Science fiction');
-- INSERT INTO genres (libelle) VALUES ('Novella');

-- INSERT INTO utilisateurs (desactive, email, mot_de_passe_chiffre, nom, prenom, role) VALUES (false,'jeanbono@gmail.com','admin123', 'Bono', 'Jean', 'ADMINISTRATEUR');
-- INSERT INTO utilisateurs (desactive, email, mot_de_passe_chiffre, nom, prenom, role) VALUES (false,'jeanemar@gmail.com','biblio123', 'Emar', 'Jean', 'BIBLIOTHECAIRE');
-- INSERT INTO utilisateurs (desactive, email, mot_de_passe_chiffre, nom, prenom, role) VALUES (false,'jeanbonboeur@gmail.com','user123', 'Bonboeur', 'Jean', 'UTILISATEUR');
-- INSERT INTO utilisateurs (desactive, email, mot_de_passe_chiffre, nom, prenom, role) VALUES (false,'jeanracine@gmail.com','user123', 'Racine', 'Jean', 'UTILISATEUR');
