-- INSERT INTO etats (libelle) VALUES ('DISPONIBLE');
-- INSERT INTO etats (libelle) VALUES ('RESERVE');
-- INSERT INTO etats (libelle) VALUES ('EMPRUNTE');
-- INSERT INTO etats (libelle) VALUES ('INUTILISABLE');
--
-- INSERT INTO statuts (libelle) VALUES ('SUR_LISTE_D_ATTENTE');
-- INSERT INTO statuts (libelle) VALUES ('EN_ATTENTE_DE_RETRAIT');
-- INSERT INTO statuts (libelle) VALUES ('CLOTUREE');
-- INSERT INTO statuts (libelle) VALUES ('ANNULEE');
--
-- INSERT INTO genres (libelle) VALUES ('ART_POETIQUE');
-- INSERT INTO genres (libelle) VALUES ('ROMAN_POLICIER');
-- INSERT INTO genres (libelle) VALUES ('FANTAISIE');
-- INSERT INTO genres (libelle) VALUES ('THEATRE');
-- INSERT INTO genres (libelle) VALUES ('ARGUMENTATIF');
-- INSERT INTO genres (libelle) VALUES ('GRAPHIQUE');
-- INSERT INTO genres (libelle) VALUES ('SCIENCE_FICTION');
-- INSERT INTO genres (libelle) VALUES ('NOVELLA');
